apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-db-deployment
spec:
  selector:
    matchLabels:
      app: web-db
  template:
    metadata:
      labels:
        app: web-db
    spec:
      containers:
      - name: web-db
        image: jhonatang7/assignment_emergent_tech_2:mysql-image
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
      - name: flask-app
        image: jhonatang7/assignment_emergent_tech_2:flask-image
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 81

---
apiVersion: v1
kind: Service
metadata:
  name: web-db-service
spec:
  type: ClusterIP
  selector:
    app: web-db
  ports:
  - name: "mysql"
    port: 3306
    targetPort: 3306
    