#!/bin/bash
apt-get update
apt-get install -y python3-pip
cd /opt
mkdir app
cd app
git clone https://github.com/SofieTorch/assignment_emergent_tech_2.git
cd assignment_emergent_tech_2/web-db/flask_app
pip3 install -r requirements.txt
python3 app.py
